apiVersion: apps/v1
kind: Deployment
metadata:
  name: maverick-code
  labels:
    app: maverick-code
spec:
  replicas: 2
  selector:
    matchLabels:
      app: maverick-code
  template:
    metadata:
      labels:
        app: maverick-code
    spec:
      containers:
      - name: maverick-code
        image: mav-app:latest
        resources:
          requests:
            cpu: "200m"
            memory: "256Mi"
          limits:
            memory: "512Mi"
            cpu: "500m"
        ports:
        - containerPort: 10000
